import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


class EmailNotifier:
    def __init__(self, smtp_host: str, smtp_port: int, smtp_user: str,
                 smtp_password: str, email_from: str, email_to: str):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.smtp_user = smtp_user
        self.smtp_password = smtp_password
        self.email_from = email_from
        self.email_to = email_to

    def send_summary(self, candidates: list, month_key: str):
        subject = f"100-Bagger Screen Results — {month_key}"
        html = self._build_html(candidates, month_key)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.email_from
        msg["To"] = self.email_to
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.sendmail(self.email_from, self.email_to, msg.as_string())
            logger.info(f"Summary email sent to {self.email_to}")
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            raise

    def _build_html(self, candidates: list, month_key: str) -> str:
        rows = ""
        for c in candidates:
            rows += (
                f"<tr>"
                f"<td>{c.get('rank', '')}</td>"
                f"<td><strong>{c.get('ticker', '')}</strong></td>"
                f"<td>{c.get('name', '')}</td>"
                f"<td>{c.get('exchange', '')}</td>"
                f"<td>${c.get('market_cap', 0) / 1_000_000:.0f}M</td>"
                f"<td>{c.get('fcf_yield', 0):.1%}</td>"
                f"<td>{c.get('book_to_market', 0):.2f}</td>"
                f"<td><strong>{c.get('score', 0):.0f}</strong></td>"
                f"</tr>"
            )

        return f"""<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: Arial, sans-serif; color: #333; max-width: 900px; margin: 0 auto; padding: 24px; }}
  h1 {{ color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
  p {{ color: #555; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 16px; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }}
  td {{ padding: 9px 14px; border-bottom: 1px solid #e0e0e0; font-size: 13px; }}
  tr:nth-child(even) {{ background: #f7f7f7; }}
  tr:hover {{ background: #eef2ff; }}
  .footer {{ margin-top: 28px; font-size: 11px; color: #aaa; border-top: 1px solid #eee; padding-top: 12px; }}
</style>
</head>
<body>
  <h1>100-Bagger Screen — {month_key}</h1>
  <p>Top multibagger candidates identified this month across ASX and SGX:</p>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Ticker</th>
        <th>Company</th>
        <th>Exchange</th>
        <th>Mkt Cap</th>
        <th>FCF Yield</th>
        <th>Book/Mkt</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>
  <p class="footer">
    Generated by 100-Bagger Bot &middot; {month_key} &middot;
    Full individual reports have been committed to the repository.
  </p>
</body>
</html>"""
